---
- name: install essential packages
  pacman: "name={{ item }} state=present"
  with_items:
    # File system
    - atool
    - file
    - gzip
    - libarchive
    - p7zip
    - rsync
    - unrar
    - unzip
    - zip
    # Language
    - go
    - python
    - python2
    # Network
    - bind-tools
    - dhcpcd
    - network-manager-applet
    - networkmanager
    - nmap
    - stalonetray
    - wget
    # Security
    - gnupg
    # System tools
    - acpi
    - linux-headers
    # Version control
    - git
  become: true
