---
- name: install essential packages
  pacman: "name={{ item }} state=present"
  with_items:
    # Network
    - connman
    - nmap
    # Python
    - python-pip
    - python2-pip
    # Security
    - gnupg2
    # Version control
    - git
  become: true
