---
- name: install pacman contributed scripts
  pacman: "name={{ item }} state=present"
  with_items:
    - pacman-contrib
  become: true

- name: install pacman mirrors refresh services
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/pacman/pacman-mirrors-refresh.service
      dest: /etc/systemd/system/pacman-mirrors-refresh.service
    - src: config/pacman/pacman-mirrors-refresh.timer
      dest: /etc/systemd/system/pacman-mirrors-refresh.timer
  become: true

- name: reload pacman mirrors refresh services
  systemd: "daemon_reload=yes"
  become: true

- name: start pacman mirrors refresh services and enable timer
  systemd: "name={{ item.name }} state=started enabled={{ item.enabled }}"
  with_items:
    - name: pacman-mirrors-refresh.service
      enabled: no
    - name: pacman-mirrors-refresh.timer
      enabled: yes
  become: true
