---
- name: change user shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
