---
- name: install gnupg packages
  pacman: "name={{ item }} state=present"
  with_items:
    - gnupg
    - pinentry
  become: true

- name: create gnupg configuration directories
  file: "path={{ item.path }} state=directory"
  with_items:
    - path: "{{ ansible_env.HOME }}/.gnupg"

- name: install gnupg configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/gnupg/gpg-agent.conf
      dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"

- name: register private pgp key existence
  command: bash -c "gpg2 --list-keys | grep '{{ gpg_email }}'"
  ignore_errors: yes
  register: private_pgp_key_existence

- name: import private pgp key
  command: bash -c "gpg2 --batch --import <(echo '{{ gpg_key }}')"
  when: private_pgp_key_existence.failed and gpg_key != ""
