---
- name: install zsh packages
  pacman: "name={{ item }} state=present"
  with_items:
    - zsh
  become: true

- name: install zgen
  git:
    repo: https://github.com/tarjoilija/zgen.git
    dest: "{{ ansible_env.HOME }}/.zgen"

- name: install zsh configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/zsh/.zprofile
      dest: "{{ ansible_env.HOME }}/.zprofile"
    - src: config/zsh/.zshenv
      dest: "{{ ansible_env.HOME }}/.zshenv"
    - src: config/zsh/.zshrc
      dest: "{{ ansible_env.HOME }}/.zshrc"
    - src: config/zsh/.zsh_plugins
      dest: "{{ ansible_env.HOME }}/.zsh_plugins"
    - src: themes/base16-grayscale-dark/zsh
      dest: "{{ ansible_env.HOME }}/.zsh_theme"

- name: install zsh plugins
  command: >
    /bin/zsh -c "ZGEN_AUTOLOAD_COMPINIT=0; . {{ ansible_env.HOME }}/.zsh_plugins"
