---
- name: install docker packages
  pacman: "name={{ item }} state=present"
  with_items:
    - docker
    - docker-compose
  become: true

- name: create docker configuration directories
  file: "path={{ item.path }} state=directory"
  with_items:
    - path: "{{ ansible_env.HOME }}/.docker"

- name: install docker configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/docker/config.json
      dest: "{{ ansible_env.HOME }}/.docker/config.json"

- name: add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true

- name: reload docker service
  systemd: "daemon_reload=yes"
  become: true

- name: start docker service
  systemd:
    name: docker.service
    state: started
    enabled: yes
  become: true
