---
- name: install bluetooth packages
  pacman: "name={{ item }} state=present"
  with_items:
    - bluez
    - bluez-utils
  become: true

- name: add user to lp group
  user:
    name: "{{ ansible_user_id }}"
    groups: lp
    append: yes
  become: true
