---
- name: install tlp packages
  pacman: "name={{ item }} state=present"
  with_items:
    - tlp
    - ethtool
    - smartmontools
    - x86_energy_perf_policy
  become: true

- name: install tlp configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/tlp/config
      dest: /etc/default/tlp
  become: true

- name: reload tlp configurations
  systemd: "daemon_reload=yes"
  become: true

- name: start tlp services
  systemd:
    name: tlp.service
    state: started
    enabled: yes
  become: true
