---
- name: clone hid-apple-plugboard-git-dkms-kestrel
  git:
    repo: https://gitlab.com/gavinkflam/hid-apple-plugboard-git-dkms-kestrel.git
    dest: "{{ ansible_env.HOME }}/.pkgs/hid-apple-plugboard-git-dkms-kestrel"

- name: register hid-apple-plugboard-git-dkms-kestrel package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/hid-apple-plugboard-git-dkms-kestrel"
  register: package_path

- name: build hid-apple-plugboard-git-dkms-kestrel
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/hid-apple-plugboard-git-dkms-kestrel"
    creates: "{{ package_path.stdout }}"

- name: install hid-apple-plugboard-git-dkms-kestrel
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true
