---
- name: clone brightnessctl
  git:
    repo: https://aur.archlinux.org/brightnessctl.git
    dest: "{{ ansible_env.HOME }}/.pkgs/brightnessctl"

- name: register brightnessctl package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/brightnessctl"
  register: package_path

- name: build brightnessctl
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/brightnessctl"
    creates: "{{ package_path.stdout }}"

- name: install brightnessctl
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

- name: add user to video and input group
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - video
      - input
    append: yes
  become: true
