---
- name: clone brightnessctl-git
  git:
    repo: https://aur.archlinux.org/brightnessctl-git.git
    dest: "{{ ansible_env.HOME }}/.pkgs/brightnessctl-git"

- name: register brightnessctl-git package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/brightnessctl-git"
  register: package_path

- name: build brightnessctl-git
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/brightnessctl-git"
    creates: "{{ package_path.stdout }}"

- name: install brightnessctl-git
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

- name: add user to video and input group
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - video
      - input
    append: yes
  become: true
