---
- name: clone python undervolt
  git:
    repo: https://gitlab.com/gavinkflam/python-undervolt.git
    dest: "{{ ansible_env.HOME }}/.pkgs/python-undervolt"

- name: register python undervolt package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/python-undervolt"
  register: package_path

- name: build python undervolt
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/python-undervolt"
    creates: "{{ package_path.stdout }}"

- name: install python undervolt
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

- name: install undervolt services
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/undervolt/undervolt.service
      dest: /etc/systemd/system/undervolt.service
    - src: config/undervolt/undervolt.timer
      dest: /etc/systemd/system/undervolt.timer
  become: true

- name: reload undervolt configurations
  systemd: "daemon_reload=yes"
  become: true

- name: start undervolt services and enable undervolt timer
  systemd: "name={{ item.name }} state=started enabled={{ item.enabled }}"
  with_items:
    - name: undervolt.service
      enabled: no
    - name: undervolt.timer
      enabled: yes
  become: true
