---
- name: clone intel-undervolt
  git:
    repo: https://aur.archlinux.org/intel-undervolt.git
    dest: "{{ ansible_env.HOME }}/.pkgs/intel-undervolt"

- name: register intel-undervolt package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/intel-undervolt"
  register: package_path

- name: build intel-undervolt
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/intel-undervolt"
    creates: "{{ package_path.stdout }}"

- name: install intel-undervolt
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

- name: install intel-undervolt configurations
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/undervolt/intel-undervolt.conf
      dest: /etc/intel-undervolt.conf
  become: true

- name: reload intel-undervolt configurations
  systemd: "daemon_reload=yes"
  become: true

- name: start intel-undervolt service
  systemd:
    name: intel-undervolt.service
    state: started
    enabled: yes
  become: true
