---
- name: install dwm peripheral packages
  pacman: "name={{ item }} state=present"
  with_items:
    - alsa-lib
    - dmenu
    - feh
    - physlock
    - unclutter
    - xorg-server
    - xorg-xinit
    - xorg-xset
    - xss-lock
  become: true

# dwm
- name: clone dwm
  git:
    repo: https://gitlab.com/gavinkflam/dwm.git
    dest: "{{ ansible_env.HOME }}/.pkgs/dwm"

- name: register dwm package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/dwm"
  register: package_path

- name: build dwm
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/dwm"
    creates: "{{ package_path.stdout }}"

- name: install dwm
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# slstatus
- name: clone slstatus
  git:
    repo: https://gitlab.com/gavinkflam/slstatus-git.git
    dest: "{{ ansible_env.HOME }}/.pkgs/slstatus-git"

- name: register slstatus package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/slstatus-git"
  register: package_path

- name: build slstatus
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/slstatus-git"
    creates: "{{ package_path.stdout }}"

- name: install slstatus
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# xorg
- name: install xorg configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/xorg/.xinitrc
      dest: "{{ ansible_env.HOME }}/.xinitrc"

- name: install wallpaper
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: wallpapers/grayscale-footbridge.jpg
      dest: "{{ ansible_env.HOME }}/wallpaper.jpg"
