---
- name: install dwm peripheral packages
  pacman: "name={{ item }} state=present"
  with_items:
    # Alsa library to compile slstatus
    - alsa-lib
    # Hiding mouse cursor
    - unclutter
    # Lock screen
    - physlock
    - xss-lock
    # Multihead
    - xorg-xrandr
    # Wallpaper
    - feh
    # X11
    - xorg-server
    # X initialization
    - xorg-xinit
    # X preference
    - xorg-xset
  become: true

# dwm
- name: clone dwm
  git:
    repo: https://github.com/gavinkflam/dwm.git
    dest: "{{ ansible_env.HOME }}/.pkgs/dwm"

- name: register dwm package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/dwm"
  register: package_path

- name: build dwm
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/dwm"
    creates: "{{ package_path.stdout }}"

- name: install dwm
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# dmenu
- name: clone dmenu-git
  git:
    repo: https://github.com/gavinkflam/dmenu-git.git
    dest: "{{ ansible_env.HOME }}/.pkgs/dmenu-git"

- name: register dmenu-git package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/dmenu-git"
  register: package_path

- name: build dmenu-git
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/dmenu-git"
    creates: "{{ package_path.stdout }}"

- name: install dmenu-git
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# slstatus
- name: clone slstatus
  git:
    repo: https://github.com/gavinkflam/slstatus-git.git
    dest: "{{ ansible_env.HOME }}/.pkgs/slstatus-git"

- name: register slstatus package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/slstatus-git"
  register: package_path

- name: build slstatus
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/slstatus-git"
    creates: "{{ package_path.stdout }}"

- name: install slstatus
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# xorg
- name: install xorg configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/xorg/.xinitrc
      dest: "{{ ansible_env.HOME }}/.xinitrc"

- name: install wallpaper
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: wallpapers/grayscale-footbridge.jpg
      dest: "{{ ansible_env.HOME }}/wallpaper.jpg"

# mesa
- name: install mesa configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/mesa/.drirc
      dest: "{{ ansible_env.HOME }}/.drirc"
