---
- name: install gtk packages
  pacman: "name={{ item }} state=present"
  with_items:
    # Configuration tool
    - lxappearance
    # Icon
    - breeze-icons
    # Theme
    - arc-solid-gtk-theme
    - gnome-themes-extra
  become: true

- name: clone xcursor breeze
  git:
    repo: https://gitlab.com/gavinkflam/xcursor-breeze.git
    dest: "{{ ansible_env.HOME }}/.pkgs/xcursor-breeze"

- name: register xcursor breeze package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/xcursor-breeze"
  register: package_path

- name: build xcursor breeze
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/xcursor-breeze"
    creates: "{{ package_path.stdout }}"

- name: install xcursor breeze
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true
