---
- name: install gtk packages
  pacman: "name={{ item }} state=present"
  with_items:
    # Configuration tool
    - lxappearance
    # Icon
    - breeze-icons
    # Theme
    - arc-solid-gtk-theme
    - gnome-themes-extra
  become: true

- name: clone xcursor breeze
  git:
    repo: https://aur.archlinux.org/xcursor-breeze.git
    dest: "{{ ansible_env.HOME }}/.pkgs/xcursor-breeze"

- name: register xcursor breeze package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/xcursor-breeze"
  register: package_path

- name: build xcursor breeze
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/xcursor-breeze"
    creates: "{{ package_path.stdout }}"

- name: install xcursor breeze
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

- name: create gtk configuration directories
  file: "path={{ item.path }} state=directory"
  with_items:
    - path: "{{ ansible_env.HOME }}/.config/gtk-3.0"
    - path: "{{ ansible_env.HOME }}/.icons/default"

- name: install gtk configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/gtk/gtk-2.0/.gtkrc-2.0
      dest: "{{ ansible_env.HOME }}/.gtkrc-2.0"
    - src: config/gtk/gtk-3.0/settings.ini
      dest: "{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini"
    - src: config/gtk/icons/index.theme
      dest: "{{ ansible_env.HOME }}/.icons/default/index.theme"
