---
- name: install gui tools packages
  pacman: "name={{ item }} state=present"
  with_items:
    # Editor
    - notepadqq
    # File manager
    - pcmanfm
    # Multimedia
    - vlc
    # PDF
    - qpdfview
    # X
    - arandr
  become: true
