---
# libgcj17-bin
- name: clone libgcj17-bin
  git:
    repo: https://aur.archlinux.org/libgcj17-bin.git
    dest: "{{ ansible_env.HOME }}/.pkgs/libgcj17-bin"

- name: register libgcj17-bin package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/libgcj17-bin"
  register: package_path

- name: build libgcj17-bin
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/libgcj17-bin"
    creates: "{{ package_path.stdout }}"

- name: install libgcj17-bin
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# pdftk-bin
- name: clone pdftk-bin
  git:
    repo: https://aur.archlinux.org/pdftk-bin.git
    dest: "{{ ansible_env.HOME }}/.pkgs/pdftk-bin"

- name: register pdftk-bin package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/pdftk-bin"
  register: package_path

- name: build pdftk-bin
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/pdftk-bin"
    creates: "{{ package_path.stdout }}"

- name: install pdftk-bin
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true
