---
# stack-bin
- name: clone stack-bin
  git:
    repo: https://aur.archlinux.org/stack-bin.git
    dest: "{{ ansible_env.HOME }}/.pkgs/stack-bin"

- name: register stack-bin package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/stack-bin"
  register: package_path

- name: build stack-bin
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/stack-bin"
    creates: "{{ package_path.stdout }}"

- name: install stack-bin
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# scripts
- name: create home bin
  file: "path={{ ansible_env.HOME }}/bin state=directory"

- name: install scripts for haskell
  copy: "src={{ item.src }} dest={{ item.dest }} mode=0755"
  with_items:
    - src: scripts/haskell/ghc-pkg
      dest: "{{ ansible_env.HOME }}/bin/ghc-pkg"

# GHCi profile
- name: install ghci profile
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/haskell/.ghci
      dest: "{{ ansible_env.HOME }}/.ghci"
