---
# Clone asdf-vm repository
- name: clone asdf-vm
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ ansible_env.HOME }}/.asdf"

# Find and checkout latest version
- name: find latest asdf-vm version
  command: "git describe --abbrev=0 --tags"
  args:
    chdir: "{{ ansible_env.HOME }}/.asdf"
  register: asdf_vm_latest_version

- set_fact: "asdf_vm_latest_version={{ asdf_vm_latest_version.stdout }}"

- name: checkout latest version for asdf-vm
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ ansible_env.HOME }}/.asdf"
    version: "{{ asdf_vm_latest_version }}"

# Install configuration files
- name: install asdf-vm configuration files
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    # Profile and global versions
    - src: config/asdf/.asdfrc
      dest: "{{ ansible_env.HOME }}/.asdfrc"
    - src: config/asdf/.tool-versions
      dest: "{{ ansible_env.HOME }}/.tool-versions"
    # Ruby
    - src: config/asdf/.default-gems
      dest: "{{ ansible_env.HOME }}/.default-gems"
    # Nodejs
    - src: config/asdf/.default-npm-packages
      dest: "{{ ansible_env.HOME }}/.default-npm-packages"

# Remember path for asdf command
- set_fact: "asdf_cmd={{ ansible_env.HOME }}/.asdf/bin/asdf"

# Install asdf-java plugin and global java
- name: install asdf-java plugin
  command: >
    bash -c "{{ asdf_cmd }} plugin-list | grep java || \
             {{ asdf_cmd }} plugin-add java"

- name: install global java
  command: >
    zsh -c "{{ asdf_cmd }} install java \
              $({{ asdf_cmd }} current java | awk '{print $1}')"

# Install asdf-nodejs plugin and global nodejs
- name: install asdf-nodejs plugin
  command: >
    bash -c "{{ asdf_cmd }} plugin-list | grep nodejs || \
             {{ asdf_cmd }} plugin-add nodejs"

- name: import nodejs release keys
  command: >
    bash {{ ansible_env.HOME }}/.asdf/plugins/nodejs/bin/import-release-team-keyring

- name: install global nodejs
  command: >
    zsh -c "{{ asdf_cmd }} install nodejs \
              $({{ asdf_cmd }} current nodejs | awk '{print $1}')"

# Install asdf-ocaml plugin and global ocaml
- name: install asdf-ocaml plugin
  command: >
    bash -c "{{ asdf_cmd }} plugin-list | grep ocaml || \
             {{ asdf_cmd }} plugin-add ocaml"

- name: install global ocaml
  command: >
    zsh -c "{{ asdf_cmd }} install ocaml \
              $({{ asdf_cmd }} current ocaml | awk '{print $1}')"

# Install asdf-opam plugin and global opam
- name: install asdf-opam plugin
  command: >
    bash -c "{{ asdf_cmd }} plugin-list | grep opam || \
             {{ asdf_cmd }} plugin-add opam"

- name: install global opam
  command: >
    zsh -c "{{ asdf_cmd }} install opam \
              $({{ asdf_cmd }} current opam | awk '{print $1}')"

# Initialize opam

- name: install opam dependencies
  pacman: "name={{ item }} state=present"
  with_items:
    - bubblewrap
  become: true

- name: find opam path
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf which opam"
  register: opam_cmd

- set_fact: "opam_cmd={{ opam_cmd.stdout }}"

- name: initialize opam
  command: >
    bash -c "{{ opam_cmd }} init --disable-shell-hook"

# Install asdf-ruby plugin and global ruby
- name: install asdf-ruby plugin
  command: >
    bash -c "{{ asdf_cmd }} plugin-list | grep ruby || \
             {{ asdf_cmd }} plugin-add ruby"

- name: install global ruby
  command: >
    zsh -c "{{ asdf_cmd }} install ruby \
              $({{ asdf_cmd }} current ruby | awk '{print $1}')"

# Install asdf-python plugin and global python
- name: install asdf-python plugin
  command: >
    bash -c "{{ asdf_cmd }} plugin-list | grep python || \
             {{ asdf_cmd }} plugin-add python"

- name: install global python3
  command: >
    zsh -c "{{ asdf_cmd }} install python \
              $({{ asdf_cmd }} current python | awk '{print $1}')"

- name: install global python2
  command: >
    zsh -c "{{ asdf_cmd }} install python \
              $({{ asdf_cmd }} current python | awk '{print $2}')"

# Install asdf-sbt plugin and global sbt
- name: install asdf-sbt plugin
  command: >
    bash -c "{{ asdf_cmd }} plugin-list | grep sbt || \
             {{ asdf_cmd }} plugin-add sbt https://github.com/gabrielelana/asdf-sbt"

- name: install global sbt
  command: >
    zsh -c "{{ asdf_cmd }} install sbt \
              $({{ asdf_cmd }} current sbt | awk '{print $1}')"
