---
# Install dummy Java environment
- name: clone dummy-java-environment
  git:
    repo: https://github.com/gavinkflam/dummy-java-environment.git
    dest: "{{ ansible_env.HOME }}/.pkgs/dummy-java-environment"

- name: register dummy-java-environment package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/dummy-java-environment"
  register: package_path

- name: build dummy-java-environment
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/dummy-java-environment"
    creates: "{{ package_path.stdout }}"

- name: install dummy-java-environment
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# Install Clojure CLI tools
- name: install cloure cli tools
  pacman: "name={{ item }} state=present"
  with_items:
    - clojure
    - rlwrap
  become: true

# Download leiningen script
- name: download leiningen script
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: "{{ ansible_env.HOME }}/bin/lein"
    mode: 0755

# Find java path
- name: find java path
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf which java"
  register: java_cmd

- set_fact: "java_cmd={{ java_cmd.stdout }}"

# Download leiningen self-install package
- name: download leiningen self-install package
  command: >
    zsh -c "JAVA_CMD={{ java_cmd }} {{ ansible_env.HOME }}/bin/lein -v"

# Install Leiningen profile
- name: install leiningen profile
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/clojure/profiles.clj
      dest: "{{ ansible_env.HOME }}/.lein/profiles.clj"

# Install shadow-cljs profile
- name: install shadow-cljs profile
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
    - src: config/clojure/shadow-cljs-config.edn
      dest: "{{ ansible_env.HOME }}/.shadow-cljs/config.edn"
