---
- name: install dotnet packages
  pacman: "name={{ item }} state=present"
  with_items:
    - dotnet-sdk
    - mono
  become: true

# msbuild
- name: clone msbuild-stable
  git:
    repo: https://aur.archlinux.org/msbuild-stable.git
    dest: "{{ ansible_env.HOME }}/.pkgs/msbuild-stable"

- name: register msbuild-stable package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/msbuild-stable"
  register: package_path

- name: build msbuild-stable
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/msbuild-stable"
    creates: "{{ package_path.stdout }}"

- name: install msbuild-stable
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true

# fsharp
- name: clone fsharp
  git:
    repo: https://aur.archlinux.org/fsharp.git
    dest: "{{ ansible_env.HOME }}/.pkgs/fsharp"

- name: register fsharp package path
  command: makepkg --packagelist
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/fsharp"
  register: package_path

- name: build fsharp
  command: makepkg
  args:
    chdir: "{{ ansible_env.HOME }}/.pkgs/fsharp"
    creates: "{{ package_path.stdout }}"

- name: install fsharp
  command: "pacman --needed --noconfirm -U {{ package_path.stdout }}"
  become: true
