---
- name: refresh package list
  pacman:
    update_cache: yes
  become: true

- name: install essential packages
  include_tasks: 00_essential_packages.yml

- name: configure user
  include_tasks: 10_configure_user.yml

- name: configure cli
  include_tasks: 20_cli.yml

- name: configure neovim
  include_tasks: 21_neovim.yml

- name: configure docker
  include_tasks: 30_docker.yml

- name: configure ansible
  include_tasks: 31_ansible.yml

- name: configure pass
  include_tasks: 40_pass.yml

- name: configurea vpn
  include_tasks: 41_vpn.yml

- name: configure gui apps
  include_tasks: 60_gui_apps.yml
