---
# Gather extra facts
- name: register dmi product name
  command: >
    bash -c "dmidecode --type 1 | grep 'Product Name' | awk '{print $3}'"
  register: dmi_product_name
  tags: always
  become: true

- set_fact: "dmi_product_name={{ dmi_product_name.stdout }}"
  tags: always

- name: register linux version
  command: uname -r
  register: linux_version
  tags: always

- set_fact: "linux_version={{ linux_version.stdout }}"
  tags: always

# Refresh package list
- name: refresh package list
  pacman:
    update_cache: yes
  become: true
  tags:
    - refresh_package_list

# Work on subtasks
- name: configure essential packages
  import_tasks: 00_essential_packages.yml
  tags:
    - configure_essential_packages

- name: configure git
  import_tasks: 11_configure_git.yml
  tags:
    - configure_git

- name: configure sshd
  import_tasks: 12_configure_sshd.yml
  tags:
    - configure_sshd

- name: configure logind
  import_tasks: 13_configure_logind.yml
  tags:
    - configure_logind

- name: configure gnupg
  import_tasks: 14_configure_gnupg.yml
  tags:
    - configure_gnupg

- name: configure setterm
  import_tasks: 15_setterm.yml
  tags:
    - configure_setterm

- name: configure zsh
  import_tasks: 20_zsh.yml
  tags:
    - configure_zsh

- name: configure tmux
  import_tasks: 21_tmux.yml
  tags:
    - configure_tmux

- name: configure neovim
  import_tasks: 22_neovim.yml
  tags:
    - configure_neovim

- name: configure ranger
  import_tasks: 23_ranger.yml
  tags:
    - configure_ranger

- name: configure docker
  import_tasks: 30_docker.yml
  tags:
    - configure_docker

- name: configure ansible
  import_tasks: 31_ansible.yml
  tags:
    - configure_ansible

- name: configure pass
  import_tasks: 40_pass.yml
  tags:
    - configure_pass

- name: configure vpn
  import_tasks: 41_vpn.yml
  tags:
    - configure_vpn

- name: configure docker credential pass
  import_tasks: 42_docker_credential_pass.yml
  tags:
    - configure_docker_credential_pass

- name: configure wifi
  import_tasks: 50_wifi.yml
  tags:
    - configure_wifi
  when: dmi_product_name is search('MacBook')

- name: configure bluetooth
  import_tasks: 51_bluetooth.yml
  tags:
    - configure_bluetooth
  when: dmi_product_name is search('MacBook')

- name: configure tlp
  import_tasks: 52_tlp.yml
  tags:
    - configure_tlp
  when: dmi_product_name is search('MacBook')

- name: configure macbook keyboard remap
  import_tasks: 53_macbook_keyboard_remap.yml
  tags:
    - configure_macbook_keyboard_remap
  when: dmi_product_name is search('MacBook')

- name: configure brightnessctl
  import_tasks: 54_brightnessctl.yml
  tags:
    - configure_brightnessctl
  when: dmi_product_name is search('MacBook')

- name: configure snd hda intel
  import_tasks: 55_snd_hda_intel.yml
  tags:
    - configure_snd_hda_intel
  when: dmi_product_name is search('MacBook')

- name: configure facetime hd
  import_tasks: 56_facetime_hd.yml
  tags:
    - configure_facetime_hd
  when: dmi_product_name is search('MacBook')

- name: configure undervolt
  import_tasks: 57_undervolt.yml
  tags:
    - configure_undervolt
  when: dmi_product_name is search('MacBook')

- name: configure gui apps
  import_tasks: 60_gui_apps.yml
  tags:
    - configure_gui_apps

- name: configure i3 gaps
  import_tasks: 61_i3_gaps.yml
  tags:
    - configure_i3_gaps
