version: "3"

services:
  vila:
    image: gavinkflam/vila:latest
    volumes:
      - ~/.ssh:/home/gavin/.ssh
      - ~/dev:/home/gavin/dev
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "$VILA/scripts/initialize-container && tail -f /dev/null"
