#!/bin/bash

set -eEuo pipefail
shopt -s lastpipe

vila_root="$(dirname "$(cd "$(dirname "$0")" && pwd)")"

# shellcheck source=scripts/install_aconfmgr
source "$vila_root/vila/scripts/install_aconfmgr"

# Apply configurations
echo -e '====> Vila: Apply aconfmgr'
cd "$aconfmgr_path" && ./aconfmgr -c "$vila_root/aconfmgr" apply

echo -e '====> Vila: Apply ninah'
"$vila_root/ninah/apply"

echo -e '====> Vila: Apply systemdcfg'
"$vila_root/systemdcfg/apply"

echo -e '====> Vila: Apply usercfg'
"$vila_root/usercfg/apply"
