#!/bin/bash

set -eEuo pipefail
shopt -s lastpipe

vila_root="$(dirname "$(cd "$(dirname "$0")" && pwd)")"

# Install aconfmgr
aconfmgr_path="$HOME/.aconfmgr"
if [[ -d "$aconfmgr_path" ]]; then
  echo -e '====> Vila: aconfmgr is present, pulling updates'
  cd "$aconfmgr_path" && git pull
else
  echo -e '====> Vila: Clone aconfmgr'
  git clone https://github.com/CyberShadow/aconfmgr.git "$aconfmgr_path"
fi

# Apply configurations
echo -e '====> Vila: Apply aconfmgr'
cd "$aconfmgr_path" && ./aconfmgr -c "$vila_root/aconfmgr" apply

echo -e '====> Vila: Apply ninah'
"$vila_root/ninah/apply"

echo -e '====> Vila: Apply usercfg'
"$vila_root/usercfg/apply"
