#!/bin/bash

set -eEuo pipefail
shopt -s lastpipe

aconfmgr_path="$HOME/.aconfmgr"
if [[ -d "$aconfmgr_path" ]]; then
  echo -e '====> Vila: aconfmgr is present, pulling updates'
  cd "$aconfmgr_path" && git pull
else
  echo -e '====> Vila: Clone aconfmgr'
  git clone https://github.com/CyberShadow/aconfmgr.git "$aconfmgr_path"
fi
