#!/bin/bash

# Check if the user is in a tmux session
if [[ -z "$TMUX" ]]; then
  echo -e 'You are not in a tmux session'
  exit 1
fi

# Split a tiny pane without changing focus and copy tmux buffer to clipboard
tmux split-window -v -d -l 0 'tmux showb | xclip -selection c; exit'
