#!/bin/bash

set -eEuo pipefail
shopt -s lastpipe

systemdcfg_root="$(cd "$(dirname "$0")" && pwd)"

# shellcheck source=lib.bash
source "$systemdcfg_root/lib.bash"

# Connectivity
EnableService 'bluetooth.service'
EnableService 'NetworkManager.service'
EnableService 'systemd-resolved.service'

# GUI
EnableService 'setterm.service'

# Security
DisableService 'sshd.service'

# Time
EnableService 'ntpd.service'

# Virtualization
EnableService 'docker.service'
EnableService 'libvirtd.service'

# MacBook
EnableService 'disable-acpi-wakeups.service'
EnableService 'intel-undervolt.service'
EnableService 'tlp.service'

# Timer
EnableService 'fstrim.timer'
EnableService 'pacman-mirrors-refresh.timer'
