#!/bin/bash

# Create ssh host keys directory
if [[ ! -d "/etc/ssh/host_keys" ]]; then
  echo -e 'creating ssh host keys directory' && \
    mkdir -p "/etc/ssh/host_keys"
fi

# Generate fresh RSA key for sshd
if [[ ! -f "/etc/ssh/host_keys/ssh_host_rsa_key" ]]; then
  echo -e 'generating fresh RSA key for sshd' && \
    ssh-keygen -f /etc/ssh/host_keys/ssh_host_rsa_key -N '' -t rsa && \
    chmod 600 /etc/ssh/host_keys/ssh_host_rsa_key
fi

# Generate fresh DSA key for sshd
if [[ ! -f "/etc/ssh/host_keys/ssh_host_dsa_key" ]]; then
  echo -e 'generating fresh DSA key for sshd' && \
    ssh-keygen -f /etc/ssh/host_keys/ssh_host_dsa_key -N '' -t dsa && \
    chmod 600 /etc/ssh/host_keys/ssh_host_dsa_key
fi
