#!/bin/bash

# Fix ownership for binded Docker socket
if [[
  -e /var/run/docker.sock &&
  "ls -ln1 /var/run/docker.sock | awk '{print $3}'" != $UID
]]; then
  echo -e 'fixing ownership for docker.sock' && \
    sudo chown $UID:$GID /var/run/docker.sock
fi

# Generate fresh host keys for sshd
sudo $VILA/scripts/generate-host-keys

# Prepare run directory for sshd
if [[ ! -d "/var/run/sshd" ]]; then
  echo -e 'creating run directory for sshd' && \
    sudo mkdir -p /var/run/sshd
fi

exec "$@"
