#!/bin/bash

# Check if inside sudo
if [[ "$EUID" -ne 0 ]]; then
  echo -e 'you must run with sudo'
  exit
fi

# Install packages
echo -e 'installing packages' && \
  pacman -Sy --noconfirm --needed \
    tlp \
    ethtool \
    smartmontools
