#!/bin/bash

# Check if inside sudo
if [[ "$EUID" -ne 0 ]]; then
  echo -e 'you must run with sudo'
  exit
fi

uname=${uname:-gavin}

# Install packages
echo -e 'installing packages' && \
  pacman -Sy --noconfirm --needed \
    chromium \
    connman \
    docker \
    feh \
    gnupg2 \
    namcap \
    neovim \
    nmap \
    openvpn \
    pass \
    python2-neovim \
    python2-pip \
    python-neovim \
    st \
    the_silver_searcher \
    tmux \
    unclutter \
    zsh

# Docker accessibility
echo -e 'add user to docker group' && \
  usermod -a -G docker $uname

# Default shell
echo -e 'set zsh as default shell for user' && \
  chsh -s /bin/zsh $uname

# tpm
echo -e 'install tpm' && \
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm

# vim plug
echo -e 'install vim plug' && \
  curl -fLo \
    $HOME/.config/nvim/autoload/plug.vim \
    --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# zgen
echo -e 'install zgen' && \
  git clone https://github.com/tarjoilija/zgen.git $HOME/.zgen

# Cleanup
unset uname
