#!/bin/bash

# Check if inside sudo
if [[ "$EUID" -ne 0 ]]; then
  echo -e 'you must run with sudo'
  exit
fi

# Extract linux version from installed package
__linux_version=$(pacman -Q | grep '^linux[0-9]* ' | awk '{print $1}')

# Install packages
echo -e 'installing packages' && \
  pacman -Sy --noconfirm --needed \
    blueman \
    broadcom-wl-dkms \
    ${__linux_version}-headers

# Cleanup
unset __linux_version
