#!/bin/bash

set -eEuo pipefail
shopt -s lastpipe

# shellcheck source=common.bash
source "$(cd "$(dirname "$0")" && pwd)/common.bash"

declare -a repositories
repositories=(
  https://aur.archlinux.org/apulse.git
  https://aur.archlinux.org/chromium-widevine.git
  https://aur.archlinux.org/docker-credential-pass-bin.git
  https://aur.archlinux.org/intel-undervolt.git
  https://aur.archlinux.org/kubectl-bin.git
  https://aur.archlinux.org/xcursor-breeze.git
  https://github.com/gavinkflam/dmenu-git.git
  https://github.com/gavinkflam/dwm.git
  https://github.com/gavinkflam/hid-apple-plugboard-git-dkms-kestrel.git
  https://github.com/gavinkflam/slstatus-git.git
  https://github.com/gavinkflam/st.git
)

function Main() {
  dir_names="$(echo "$@" | xargs -n1 "$ninah_root/lib/ninah-repo-dir-name")"

  "$ninah_root/ninah-init"

  # Sync repos
  echo "$@" | xargs -n1 -P10 "$ninah_root/ninah-sync-repo"

  # Build packages
  echo "$dir_names" | xargs -n1 -P"$(nproc)" "$ninah_root/ninah-make"

  # Install or upgrade packages
  "$ninah_root/ninah-install-multi" "$dir_names"
}

Main "${repositories[@]}"
