#!/bin/bash

set -eEuo pipefail
shopt -s lastpipe

source "$(cd $(dirname "$0") && pwd)/common.bash"

function NinahInit() {
  if [[ -d "$makepkg_dir" ]]; then
    echo -e "====> Ninah [Init]: $makepkg_dir is present"
  else
    echo -e "====> Ninah [Init]: Create $makepkg_dir"
    mkdir -p "$makepkg_dir"
  fi
}

NinahInit "$@"
