#!/bin/bash

set -eEuo pipefail
shopt -s lastpipe

# shellcheck source=common.bash
source "$(cd "$(dirname "$0")" && pwd)/common.bash"

function NinahMake() {
  if [[ -f "$(cd "$makepkg_dir/$1" && makepkg --packagelist)" ]]; then
    echo -e "====> Ninah [Make $1]: Package is already built, skipping"
  else
    echo -e "====> Ninah [Make $1]: Make package"
    cd "$makepkg_dir/$1" && makepkg --syncdeps
  fi
}

NinahMake "$@"
