#!/bin/bash

set -eEuo pipefail
shopt -s lastpipe

# shellcheck source=common.bash
source "$(cd "$(dirname "$0")" && pwd)/common.bash"

function NinahSyncRepo() {
  dir_name="$("$ninah_root/lib/ninah-repo-dir-name" "$1")"

  if [[ -d "$makepkg_dir/$dir_name" ]]; then
    echo -e "====> Ninah [Sync $1]: Repository is already cloned, pulling updates"
    cd "$makepkg_dir/$dir_name" && git pull --rebase
  else
    echo -e "====> Ninah [Sync $1]: Clone repository"
    cd "$makepkg_dir" && git clone "$1"
  fi
}

NinahSyncRepo "$@"
